import { createServer } from 'http';
import { readFile } from 'fs/promises';
import { extname, join, normalize } from 'path';
import pkg from '/opt/node22/lib/node_modules/playwright/index.js';
const { chromium } = pkg;
const ROOT = new URL('..', import.meta.url).pathname;
const MIME = { '.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.webmanifest':'application/manifest+json' };
const server = createServer(async (req,res)=>{try{let p=decodeURIComponent(req.url.split('?')[0]);if(p==='/')p='/index.html';const f=normalize(join(ROOT,p));const d=await readFile(f);res.writeHead(200,{'Content-Type':MIME[extname(f)]||'application/octet-stream'});res.end(d);}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,r));
const base=`http://localhost:${server.address().port}/`;
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const p=await b.newPage({viewport:{width:1280,height:900}});
await p.goto(base,{waitUntil:'networkidle'});
await p.waitForSelector('.hl-card');
await p.fill('#searchBox','risk');
await p.waitForTimeout(500);
const marks = await p.$$eval('.hl-text mark', els=>els.map(e=>e.textContent));
console.log('mark count:', marks.length, 'samples:', [...new Set(marks)].slice(0,5));
await p.screenshot({path:'assets/shot-search-highlight.png'});
await b.close();server.close();
